import type { NormalizedBiletEvent } from '@/services/biletPublicApi';

/** Демо-афиша (визуал как neglinka29.ru), если API недоступен или пустой ответ. */
export const NEGLINKA_DEMO_EVENTS: NormalizedBiletEvent[] = [
  {
    id: 'demo-1',
    title: 'САЛЕМСКИЕ ВЕДЬМЫ. ПРЕМЬЕРА!',
    subtitle:
      'Спектакль по пьесе Артура Миллера — история общества, охваченного страхом и доносами.',
    dateLabel: '19:00',
    timeLabel: '19:00',
    genre: 'Драма',
    venue: 'Эрмитаж',
    age: '18+',
    author: 'Артур Миллер',
    director: 'Дмитрий Астрахан',
    isPremiere: true,
    displayDate: '14.04',
    weekday: 'ВТОРНИК',
    imageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=960&q=80',
  },
  {
    id: 'demo-2',
    title: 'ОДНАЖДЫ',
    dateLabel: '19:00',
    timeLabel: '19:00',
    genre: 'Драма',
    venue: 'Зимний сад',
    age: '18+',
    director: 'Александр Созонов',
    displayDate: '14.04',
    weekday: 'ВТОРНИК',
    imageUrl: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=960&q=80',
  },
  {
    id: 'demo-3',
    title: 'ЖЁЛТЫЙ КАРЛИК. ПРЕМЬЕРА!',
    dateLabel: '19:00',
    timeLabel: '19:00',
    genre: 'Трагикомедия',
    venue: 'Эрмитаж',
    age: '18+',
    author: 'Олег Данилов',
    director: 'Дмитрий Астрахан',
    isPremiere: true,
    displayDate: '18.04',
    weekday: 'СУББОТА',
    imageUrl: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=960&q=80',
  },
  {
    id: 'demo-4',
    title: 'ПЛУТНИ СКАПЕНА',
    dateLabel: '19:00',
    timeLabel: '19:00',
    genre: 'Комедия',
    venue: 'Зимний сад',
    age: '18+',
    author: 'Жан-Батист Мольер',
    displayDate: '16.04',
    weekday: 'ЧЕТВЕРГ',
    imageUrl: 'https://images.unsplash.com/photo-1616469829581-73993eb86b00?w=960&q=80',
  },
  {
    id: 'demo-5',
    title: 'ПЯТЬ ВЕЧЕРОВ. ПРЕМЬЕРА!',
    dateLabel: '19:00',
    timeLabel: '19:00',
    genre: 'Мелодрама',
    venue: 'Зимний сад',
    age: '16+',
    director: 'Игорь Мужжухин',
    isPremiere: true,
    displayDate: '19.04',
    weekday: 'ВОСКРЕСЕНЬЕ',
    imageUrl: 'https://images.unsplash.com/photo-1524712244904-cc2a7d1e242f?w=960&q=80',
  },
  {
    id: 'demo-6',
    title: 'КОНЦЕРТ СИМФОНИЧЕСКОЙ МУЗЫКИ',
    dateLabel: '20:00',
    timeLabel: '20:00',
    genre: 'Концерт',
    venue: 'Большой зал',
    age: '12+',
    displayDate: '22.04',
    weekday: 'ВТОРНИК',
    imageUrl: 'https://images.unsplash.com/photo-1465847899274-095bf3a71784?w=960&q=80',
  },
];
