-- Расширение списка доноров и добавление категории marketing
-- Добавляем больше доноров в каждую категорию (по 30-40 для покрытия 258 кейсов)

INSERT INTO donors (category, url, sort_order) VALUES
  -- Advertising (добавляем еще 25 доноров)
  ('advertising', 'https://www.turist-agency.ru', 16),
  ('advertising', 'https://www.photo-studio.ru', 17),
  ('advertising', 'https://www.event-agency.ru', 18),
  ('advertising', 'https://www.printing-service.ru', 19),
  ('advertising', 'https://www.web-design-studio.ru', 20),
  ('advertising', 'https://www.consulting-firm.ru', 21),
  ('advertising', 'https://www.accounting-service.ru', 22),
  ('advertising', 'https://www.cleaning-company.ru', 23),
  ('advertising', 'https://www.translation-agency.ru', 24),
  ('advertising', 'https://www.it-outsourcing.ru', 25),
  ('advertising', 'https://www.security-service.ru', 26),
  ('advertising', 'https://www.catering-service.ru', 27),
  ('advertising', 'https://www.photography-studio.ru', 28),
  ('advertising', 'https://www.video-production.ru', 29),
  ('advertising', 'https://www.marketing-agency.ru', 30),
  ('advertising', 'https://www.recruitment-agency.ru', 31),
  ('advertising', 'https://www.training-center.ru', 32),
  ('advertising', 'https://www.coaching-service.ru', 33),
  ('advertising', 'https://www.psychology-center.ru', 34),
  ('advertising', 'https://www.fitness-studio.ru', 35),
  ('advertising', 'https://www.yoga-studio.ru', 36),
  ('advertising', 'https://www.dance-studio.ru', 37),
  ('advertising', 'https://www.music-school.ru', 38),
  ('advertising', 'https://www.art-gallery.ru', 39),
  ('advertising', 'https://www.antique-shop.ru', 40),
  
  -- Design (добавляем еще 20 доноров)
  ('design', 'https://www.brand-identity.ru', 11),
  ('design', 'https://www.packaging-design.ru', 12),
  ('design', 'https://www.print-design.ru', 13),
  ('design', 'https://www.illustration-studio.ru', 14),
  ('design', 'https://www.animation-studio.ru', 15),
  ('design', 'https://www.ui-design-agency.ru', 16),
  ('design', 'https://www.ux-design-studio.ru', 17),
  ('design', 'https://www.product-design.ru', 18),
  ('design', 'https://www.interior-design-studio.ru', 19),
  ('design', 'https://www.landscape-design.ru', 20),
  ('design', 'https://www.fashion-brand.ru', 21),
  ('design', 'https://www.jewelry-brand.ru', 22),
  ('design', 'https://www.watch-brand.ru', 23),
  ('design', 'https://www.perfume-brand.ru', 24),
  ('design', 'https://www.cosmetics-brand.ru', 25),
  ('design', 'https://www.furniture-brand.ru', 26),
  ('design', 'https://www.lighting-design.ru', 27),
  ('design', 'https://www.textile-design.ru', 28),
  ('design', 'https://www.ceramic-studio.ru', 29),
  ('design', 'https://www.glass-studio.ru', 30),
  
  -- SEO (добавляем еще 20 доноров)
  ('seo', 'https://www.law-firm-seo.ru', 12),
  ('seo', 'https://www.accounting-firm-seo.ru', 13),
  ('seo', 'https://www.consulting-seo.ru', 14),
  ('seo', 'https://www.construction-seo.ru', 15),
  ('seo', 'https://www.renovation-seo.ru', 16),
  ('seo', 'https://www.plumbing-seo.ru', 17),
  ('seo', 'https://www.electrician-seo.ru', 18),
  ('seo', 'https://www.roofing-seo.ru', 19),
  ('seo', 'https://www.landscaping-seo.ru', 20),
  ('seo', 'https://www.pool-service-seo.ru', 21),
  ('seo', 'https://www.hvac-seo.ru', 22),
  ('seo', 'https://www.pest-control-seo.ru', 23),
  ('seo', 'https://www.carpet-cleaning-seo.ru', 24),
  ('seo', 'https://www.window-cleaning-seo.ru', 25),
  ('seo', 'https://www.moving-company-seo.ru', 26),
  ('seo', 'https://www.storage-facility-seo.ru', 27),
  ('seo', 'https://www.parking-service-seo.ru', 28),
  ('seo', 'https://www.security-system-seo.ru', 29),
  ('seo', 'https://www.alarm-system-seo.ru', 30),
  ('seo', 'https://www.locksmith-seo.ru', 31),
  
  -- Website (добавляем еще 20 доноров)
  ('website', 'https://www.auto-repair.ru', 13),
  ('website', 'https://www.car-wash.ru', 14),
  ('website', 'https://www.tire-service.ru', 15),
  ('website', 'https://www.gas-station.ru', 16),
  ('website', 'https://www.parking-service.ru', 17),
  ('website', 'https://www.taxi-service.ru', 18),
  ('website', 'https://www.rental-service.ru', 19),
  ('website', 'https://www.insurance-agency.ru', 20),
  ('website', 'https://www.real-estate-agency.ru', 21),
  ('website', 'https://www.property-management.ru', 22),
  ('website', 'https://www.home-inspection.ru', 23),
  ('website', 'https://www.appraisal-service.ru', 24),
  ('website', 'https://www.mortgage-broker.ru', 25),
  ('website', 'https://www.title-company.ru', 26),
  ('website', 'https://www.escrow-service.ru', 27),
  ('website', 'https://www.notary-service.ru', 28),
  ('website', 'https://www.translation-service.ru', 29),
  ('website', 'https://www.interpreting-service.ru', 30),
  ('website', 'https://www.tutoring-service.ru', 31),
  ('website', 'https://www.test-prep-center.ru', 32),
  
  -- Mobile (добавляем еще 16 доноров)
  ('mobile', 'https://www.taxi-app.ru', 5),
  ('mobile', 'https://www.delivery-app.ru', 6),
  ('mobile', 'https://www.food-app.ru', 7),
  ('mobile', 'https://www.grocery-app.ru', 8),
  ('mobile', 'https://www.pharmacy-app.ru', 9),
  ('mobile', 'https://www.booking-app.ru', 10),
  ('mobile', 'https://www.travel-app.ru', 11),
  ('mobile', 'https://www.weather-app.ru', 12),
  ('mobile', 'https://www.news-app.ru', 13),
  ('mobile', 'https://www.social-app.ru', 14),
  ('mobile', 'https://www.messaging-app.ru', 15),
  ('mobile', 'https://www.video-app.ru', 16),
  ('mobile', 'https://www.music-app.ru', 17),
  ('mobile', 'https://www.photo-app.ru', 18),
  ('mobile', 'https://www.fitness-app-2.ru', 19),
  ('mobile', 'https://www.health-app.ru', 20),
  
  -- AI (добавляем еще 17 доноров)
  ('ai', 'https://www.ai-chatbot-service.ru', 4),
  ('ai', 'https://www.ai-content-generator.ru', 5),
  ('ai', 'https://www.ai-translator.ru', 6),
  ('ai', 'https://www.ai-voice-assistant.ru', 7),
  ('ai', 'https://www.ai-image-generator.ru', 8),
  ('ai', 'https://www.ai-video-editor.ru', 9),
  ('ai', 'https://www.ai-data-analytics.ru', 10),
  ('ai', 'https://www.ai-customer-service.ru', 11),
  ('ai', 'https://www.ai-sales-assistant.ru', 12),
  ('ai', 'https://www.ai-marketing-automation.ru', 13),
  ('ai', 'https://www.ai-email-assistant.ru', 14),
  ('ai', 'https://www.ai-scheduling-assistant.ru', 15),
  ('ai', 'https://www.ai-research-assistant.ru', 16),
  ('ai', 'https://www.ai-code-assistant.ru', 17),
  ('ai', 'https://www.ai-design-assistant.ru', 18),
  ('ai', 'https://www.ai-writing-assistant.ru', 19),
  ('ai', 'https://www.ai-transcription-service.ru', 20),
  
  -- Marketing (новая категория - 30 доноров)
  ('marketing', 'https://www.digital-marketing-agency.ru', 1),
  ('marketing', 'https://www.content-marketing-agency.ru', 2),
  ('marketing', 'https://www.social-media-agency.ru', 3),
  ('marketing', 'https://www.email-marketing-service.ru', 4),
  ('marketing', 'https://www.influencer-marketing.ru', 5),
  ('marketing', 'https://www.affiliate-marketing.ru', 6),
  ('marketing', 'https://www.viral-marketing-agency.ru', 7),
  ('marketing', 'https://www.guerilla-marketing.ru', 8),
  ('marketing', 'https://www.event-marketing.ru', 9),
  ('marketing', 'https://www.experiential-marketing.ru', 10),
  ('marketing', 'https://www.brand-activation-agency.ru', 11),
  ('marketing', 'https://www.promotional-agency.ru', 12),
  ('marketing', 'https://www.trade-show-marketing.ru', 13),
  ('marketing', 'https://www.exhibition-marketing.ru', 14),
  ('marketing', 'https://www.sponsorship-agency.ru', 15),
  ('marketing', 'https://www.partnership-marketing.ru', 16),
  ('marketing', 'https://www.co-marketing-agency.ru', 17),
  ('marketing', 'https://www.cross-promotion-agency.ru', 18),
  ('marketing', 'https://www.loyalty-program-agency.ru', 19),
  ('marketing', 'https://www.customer-retention-agency.ru', 20),
  ('marketing', 'https://www.customer-acquisition-agency.ru', 21),
  ('marketing', 'https://www.lead-generation-agency.ru', 22),
  ('marketing', 'https://www.conversion-optimization.ru', 23),
  ('marketing', 'https://www.landing-page-agency.ru', 24),
  ('marketing', 'https://www.funnel-optimization.ru', 25),
  ('marketing', 'https://www.marketing-automation-agency.ru', 26),
  ('marketing', 'https://www.crm-implementation-agency.ru', 27),
  ('marketing', 'https://www.marketing-analytics-agency.ru', 28),
  ('marketing', 'https://www.marketing-research-agency.ru', 29),
  ('marketing', 'https://www.marketing-consulting-agency.ru', 30)
ON CONFLICT (category, url) DO NOTHING;

